### ISSUE TITLE
add support for getting Docker Image from Different Registry via values File

### ISSUE THREAD

**Issue by colinbjohnson** [NangoHQ/nango-helm-charts#7]
There are particular customers that may require the use of an image from an internal Docker Image Repository. With the current helm chart configuration that is not possible.

Example from "[main/charts/nango/templates/server/server-deployment.yaml](https://github.com/NangoHQ/nango-helm-charts/blob/main/charts/nango/templates/server/server-deployment.yaml#L16-L20)"

```yaml
spec:
  containers:
    - name: {{ .Values.server.name | default "nango-server" }}
      image: nangohq/nango:prod-{{ .Values.server.tag | default .Values.shared.tag }}
      imagePullPolicy: {{ .Values.imagePullPolicy  | default "Always" }}
      args: ["node", "packages/server/dist/server.js"]
```

We might consider submitting a PR for this if the Nango organization agrees this might be valuable for (typically) enterprise type customers with security requirements.
